---
version: '3.7'
services:
  pmm-x:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pmm-x

    # for delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    ports:
      - "80:80"
      - "443:443"

#    volumes:
#      - "/Users/am/dev/implex/percona/ui-tracking/grafana/public:/usr/share/grafana/public"

      # see https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug#what-to-do
    ulimits:
      memlock: 67108864
