---
version: '3.9'
services:
  be:
    profiles:
      - build
    image: golang:1.19.2-buster
    container_name: grafana-be-build
    entrypoint: [ "sh", "-c", "/build/build-be.sh" ]
    volumes:
      - ./:/build
  fe:
    profiles:
      - build
    image: node:16.17-buster
    container_name: grafana-fe-build
    entrypoint: [ "sh", "-c", "/build/build-fe.sh" ]
    volumes:
      - ./:/build
  pack:
    profiles:
      - pack
    image: ubuntu:22.04
    container_name: grafana-pack
    entrypoint: [ "sh", "-c", "/build/build-pack.sh" ]
    volumes:
      - ./:/build
