---
version: '3.9'
services:
  be:
    profiles:
      - be-build
    image: golang:1.19.2-buster
    container_name: be-build
    entrypoint: [ "sh", "-c", "/build/build-be.sh" ]
    volumes:
      - "./:/build:z"
  fe:
    profiles:
      - fe-build
    image: node:16.17-buster
    container_name: fe-build
    entrypoint: [ "sh", "-c", "/build/build-fe.sh" ]
    volumes:
      - "./:/build:z"
  fe-pack:
    env_file:
      - .env
    profiles:
      - pack-fe
    image: ubuntu:22.04
    container_name: fe-pack
    entrypoint: [ "sh", "-c", "/build/build-fe-pack.sh" ]
    volumes:
      - "./:/build:z"
