---
version: '3.9'
services:
  be:
    profiles:
      - be-build
    image: golang:1.19.5-bullseye
    container_name: x-core-be-build
    entrypoint: [ "sh", "-c", "/build/build-be.sh" ]
    volumes:
      - "./:/build"
  be-pack:
    env_file:
      - .env
    profiles:
      - be-pack
    image: ubuntu:22.04
    container_name: x-core-be-pack
    entrypoint: [ "sh", "-c", "/build/build-be-pack.sh" ]
    volumes:
      - "./:/build"
