---
version: '3.9'
services:
  be:
    profiles:
      - be-build
    image: golang:1.20.1-bullseye
    container_name: x-core-be-build
    entrypoint: [ "sh", "-c", "/build/build-be.sh" ]
    volumes:
      - "./:/build"
      # caching
      - go-modules:/root/go/pkg/mod
      - root-cache:/root/.cache
  be-pack:
    env_file:
      - .env
    profiles:
      - be-pack
    image: ubuntu:22.04
    container_name: x-core-be-pack
    entrypoint: [ "sh", "-c", "/build/build-be-pack.sh" ]
    volumes:
      - "./:/build"
      # caching
      - go-modules:/root/go/pkg/mod
      - root-cache:/root/.cache

volumes:
  go-modules:
  root-cache:
