name: Docker Image CI

on:
  push:
    branches: [ "amd64" ]
  pull_request:
    branches: [ "FB/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: build
        run: make build-amd64
