name: Docker Image CI

on:
  push:
    branches: [ "gha", "main" ]
  pull_request:
    branches: [ "FB/*" ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - {machine: [self-hosted, X64], arch: amd64, key: hosted-amd64 }
          - {machine: [self-hosted, ARM64], arch: arm64, key: hosted-arm64 }
    runs-on: ${{ matrix.target.machine }}
    steps:
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.target.key }}-deps
      - name: Prepare
        run: make prepare
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build
        run: TAG=${{ github.ref_name }} make publish-${{ matrix.target.arch }}
