name: Docker Image CI

on:
  push:
    branches: [ "gha", "main" ]
  pull_request:
    branches: [ "FB/*" ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - {machine: [self-hosted, X64], arch: amd64 }
    runs-on: ${{ matrix.target.machine }}
    steps:
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.target.machine }}-${{ matrix.target.arch }}-deps
      - name: Prepare
        run: make prepare
      - name: Build
        run: make build-${{ matrix.target.arch }}
