name: Docker Image CI

on:
  push:
    branches: [ "gha", "main" ]
  pull_request:
    branches: [ "FB/*" ]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - X64
    runs-on: [self-hosted, ${{ matrix.arch }}]
    steps:
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.arch }}-deps
      - name: Prepare
        run: make prepare
      - name: Build
        run: make build-amd64
