name: Test

on:
  push:
    branches: [ "gha", "main" ]
  pull_request:
    branches: [ "FB/*" ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - {machine: [ubuntu-latest], arch: amd64, key: hosted-amd64 }
    runs-on: ${{ matrix.target.machine }}
    steps:
      - name: Build
        run: TAG="`echo "${{ github.ref_name }}" | sed -e "s/^FB\///"`" ${{ github.ref_name }} make publish-${{ matrix.target.arch }}
