name: X:Core

on:
  ##  push:
  ##    branches: [ "main" ]
  push:
    branches:
      - "X/**"
    paths:
      - "components/core/**"

jobs:
  core-be:
    strategy:
      matrix:
        target:
          - {machine: [self-hosted, star01] }
          - {machine: [buildjet-4vcpu-ubuntu-2204-arm]}
    runs-on: ${{ matrix.target.machine }}
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        if: ${{ contains(matrix.target.machine, 'star01') }}
        run: |
          echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S rm -rf ${GITHUB_WORKSPACE}
          mkdir ${GITHUB_WORKSPACE}
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: Build
        run: TAG=`echo "${{ github.ref_name }}" | sed -e "s/^X\///"` make build-x-core-be
      - name: Upload to S3
        uses: ritbl/gha-aws@v1.0.1
        with:
          entrypoint: "./s3-publish.sh"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"