#name: X:Core Image
#
#on:
##  push:
##    branches: [ "main" ]
#  push:
#    branches:
#      - "X/**"
#    paths:
#      - "components/core/**"
#
#jobs:
#  build:
#    strategy:
#      matrix:
#        target:
#          - {machine: [self-hosted, star01], key: hosted-amd64 }
#    runs-on: ${{ matrix.target.machine }}
#    steps:
#      - name: Check out code
#        uses: percona-platform/checkout@v3
#      - name: Cache
#        uses: actions/cache@v3
#        with:
#          path: deps
#          key: ${{ matrix.target.key }}-x-core-deps
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PAT }}
#      - name: Build
#        run: TAG=`echo "${{ github.ref_name }}" | sed -e "s/^X\///"` make publish-x-core
