name: X:Grafana FE

on:
#  push:
#    branches: [ "main" ]
  push:
    branches:
      - "rework-build-and-cache"
#    paths:
#      - "components/grafana/**"

jobs:
#  build-fe:
#    strategy:
#      matrix:
#        target:
#          - {machine: [self-hosted, star01]}
#    runs-on: ${{ matrix.target.machine }}
##    runs-on: buildjet-2vcpu-ubuntu-2204
#    steps:
#      - name: cleanup #https://github.com/actions/checkout/issues/211
#        if: ${{ contains(matrix.target.machine, 'star01') }}
#        run: |
#          echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S rm -rf ${GITHUB_WORKSPACE}
#          mkdir ${GITHUB_WORKSPACE}
#      - name: Check out code
#        uses: percona-platform/checkout@v3
#      - name: Build
#        run: TAG=0.2.0 make build-x-grafana-fe
#      - name: Upload to S3
#        uses: ritbl/gha-aws@v1.0.1
#        with:
#          entrypoint: "./s3-publish.sh"
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
#          AWS_DEFAULT_REGION: "eu-central-1"
  build-be:
    strategy:
      matrix:
        target:
#          - {machine: [self-hosted, star01], arch: amd64 }
#          - {machine: [self-hosted] }
          - {machine: [buildjet-2vcpu-ubuntu-2204-arm]}
    runs-on: ${{ matrix.target.machine }}
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        if: ${{ contains(matrix.target.machine, 'star01') }}
        run: |
          echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S rm -rf ${GITHUB_WORKSPACE}
          mkdir ${GITHUB_WORKSPACE}
      - name: Check out code
        uses: percona-platform/checkout@v3
      - name: Build
        run: TAG=0.3.0 make build-x-grafana-be
      - name: Upload to S3
        uses: ritbl/gha-aws@v1.0.1
        with:
          entrypoint: "./s3-publish.sh"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"